# cloudbuild.yaml
steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/my-project-406105/ankit-100921091/node-app:$COMMIT_SHA', '.']
  # Push docker image to artifactory
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/my-project-406105/ankit-100921091/node-app:$COMMIT_SHA']
options:
  defaultLogsBucketBehavior : REGIONAL_USER_OWNED_BUCKET
